[redis]
unix_socket = "/var/run/redis/redis.sock"
host        = "127.0.0.1"
port        = 6379

[redis.db_map]
eth = 0
bsc = 1
polygon = 2
base = 3
arb = 4

[chains.eth]
chain_id     = 1
rpc_http     = "http://192.168.88.167:8545"
head_poll_ms = 500

[chains.bsc]
chain_id     = 56
rpc_http     = "http://127.0.0.1:8545"
head_poll_ms = 500

[chains.polygon]
chain_id     = 137
rpc_http     = "http://127.0.0.1:8545"
head_poll_ms = 500

[chains.base]
chain_id     = 8453
rpc_http     = "http://127.0.0.1:8545"
head_poll_ms = 500

[chains.arb]
chain_id     = 42161
rpc_http     = "http://127.0.0.1:8545"
head_poll_ms = 500

[tvl]
enabled = false

[state_diff]
mode = "auto"

[v3]
enabled = true

[v4]
enabled = false

[price.eth]
source = "none"

[rpc]
retries = 3
